### ISSUE TITLE
Dependencies error reported with search

### ISSUE THREAD

**Issue by verdurin** [fizwit/easy_update#14]
Error reported with `--search` command:
```
 ./easy_update.py --rver 3.5.1 --search evodiR
Traceback (most recent call last):
  File "./easy_update.py", line 888, in <module>
    main()
  File "./easy_update.py", line 866, in main
    if eb.dependencies:
AttributeError: 'NoneType' object has no attribute 'dependencies'
```

**Comment by fizwit** [comment]
this is fixed with version 2.0.1.  Please try version 2.0.2
