### ISSUE TITLE
Error with Bioconductor update

### ISSUE THREAD

**Issue by verdurin** [fizwit/easy_update#19]
```
~/src/github/easy_update/easy_update.py R-bundle-Bioconductor-3.8-foss-2018b-R-3.6.0.eb -v --rver 3.6.0 --biocver 3.9
reading dependencies: R-3.6.0-foss-2018b.eb
               readr : 1.3.1                 (duplicate) [143, 0]
        BiocGenerics : 0.28.0 -> 0.30.0         (update) [143, 1]
             Biobase : 2.42.0 -> 2.44.0         (update) [143, 2]
           S4Vectors : 0.20.1 -> 0.22.0         (update) [143, 3]
             IRanges : 2.16.0 -> 2.18.1         (update) [143, 4]
    GenomeInfoDbData : 1.2.0 -> 1.2.1           (update) [143, 5]
        GenomeInfoDb : 1.18.1 -> 1.20.0         (update) [143, 6]
       AnnotationDbi : 1.44.0 -> 1.46.0         (update) [143, 7]
            zlibbioc : 1.28.0 -> 1.30.0         (update) [143, 8]
             XVector : 0.22.0 -> 0.24.0         (update) [143, 9]
          Biostrings : 2.50.2 -> 2.52.0         (update) [143, 10]
       GenomicRanges : 1.34.0 -> 1.36.0         (update) [143, 11]
        BiocParallel : 1.16.5 -> 1.18.0         (update) [143, 12]
             Rhtslib : 1.16.1                      (add) [143, 13]
           Rsamtools : 1.34.0 -> 2.0.0          (update) [143, 14]
        DelayedArray : 0.8.0 -> 0.10.0          (update) [143, 15]
SummarizedExperiment : 1.12.0 -> 1.14.0         (update) [143, 16]
   GenomicAlignments : 1.18.1 -> 1.20.1         (update) [143, 17]
           ShortRead : 1.40.0 -> 1.42.0         (update) [143, 18]
               graph : 1.60.0 -> 1.62.0         (update) [143, 19]
              affyio : 1.52.0 -> 1.54.0         (update) [143, 20]
      preprocessCore : 1.44.0 -> 1.46.0         (update) [143, 21]
Traceback (most recent call last):
  File "/users/software/software/src/github/easy_update/easy_update.py", line 888, in <module>
    main()
  File "/users/software/software/src/github/easy_update/easy_update.py", line 883, in main
    module = UpdateR(args, eb, dep_eb)
  File "/users/software/software/src/github/easy_update/easy_update.py", line 487, in __init__
    self.updateexts()
  File "/users/software/software/src/github/easy_update/easy_update.py", line 449, in updateexts
    self.check_package(pkg)
  File "/users/software/software/src/github/easy_update/easy_update.py", line 384, in check_package
    status = self.get_package_info(pkg)
  File "/users/software/software/src/github/easy_update/easy_update.py", line 573, in get_package_info
    status = self.get_cran_info(pkg)
  File "/users/software/software/src/github/easy_update/easy_update.py", line 518, in get_cran_info
    if self.Meta:
AttributeError: UpdateR instance has no attribute 'Meta'
```

**Comment by fizwit** [comment]
I have fixed the meta/Meta issue with the code.  Please use release 2.0.5.

easy_update will read the version information from the file if present.  -rver  --biocver flags are only used the --search flag, when no file name is given for an argument.
