### ISSUE TITLE
Traceback with --search

### ISSUE THREAD

**Issue by verdurin** [fizwit/easy_update#21]
```
$ ./easy_update.py --rver 3.6.1 --biocver 3.9 --search heatmaply
Traceback (most recent call last):
  File "./easy_update.py", line 489, in <module>
    main()
  File "./easy_update.py", line 483, in main
    UpdateR(args, eb)
  File "./easy_update.py", line 105, in __init__
    UpdateExts.__init__(self, args, eb)
  File "/home/centos/src/github/easy_update/updateexts.py", line 91, in __init__
    if eb.dep_exts:
AttributeError: 'NoneType' object has no attribute 'dep_exts'
```

**Comment by fizwit** [comment]
fixed tag 2.0.8.4

FYI, your search will produce a list of 89 modules which is a big list. If you have an existing easyconfig for R that you can use as a dependency then list it as an argument. EasyUpdate will read the exts_list and short circuit the list of dependencies.  Adding heatmaply to 3.6.1 only requires 3 dependencies the other 85 are part of the existing R module.

```
./easy_update.py ~/git/easybuild-life-sciences/fh_easyconfigs/r/R/R-3.6.1-foss-2018b.eb  --biocver 3.9 --search heatmaply
    ('TSP', '1.1-7'),
    ('qap', '0.1-1'),
    ('seriation', '1.2-8'),
    ('heatmaply', '0.16.0'),
```
