### ISSUE TITLE
Giving file path makes easy_update unhappy

### ISSUE THREAD

**Issue by surak** [fizwit/easy_update#25]
```python
./easy_annotate.py ../../easybuild-repository/Golden_Repo/r/R/R-4.0.2-gpsmkl-2020.eb 
Traceback (most recent call last):
  File "./easy_annotate.py", line 273, in <module>
    main()
  File "./easy_annotate.py", line 258, in main
    eb = FrameWork(args)
  File "/p/project/cjsc/a.strube/easy_update/framework.py", line 56, in __init__
    (head, tail) = os.path.split(fullPath)
UnboundLocalError: local variable 'fullPath' referenced before assignment
```

**Comment by fizwit** [comment]
cleaning up old issues.

**Comment by surak** [comment]
@fizwit  Was it actually fixed, or just closed without checking?

**Comment by fizwit** [comment]
R and Python modules were tested before pushing. but there is much more work to do.
