### ISSUE TITLE
Easyblock-less easyconfigs make easy_update unhappy, too. 

### ISSUE THREAD

**Issue by surak** [fizwit/easy_update#27]
For example, the latest R has no declaration of an easyblock: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb

But I get this: 
```python
./easy_annotate.py R-4.0.2-gpsmkl-2020.eb 
Traceback (most recent call last):
  File "./easy_annotate.py", line 273, in <module>
    main()
  File "./easy_annotate.py", line 258, in main
    eb = FrameWork(args)
  File "/p/project/cjsc/a.strube/easy_update/framework.py", line 83, in __init__
    self.detect_language(eb)
  File "/p/project/cjsc/a.strube/easy_update/framework.py", line 153, in detect_language
    if eb.easyblock == 'PythonPackage' or eb.easyblock == 'PythonBundle':
AttributeError: 'module' object has no attribute 'easyblock'
```

Which I assume that means python can't find Easybuild stuff.

**Comment by fizwit** [comment]
Cleaning up old issues. This has since been resolved. Checking for 
```
name = 'R'
```
