### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by pescobar** [fizwit/easy_update#5]
first of all, thank for this contribution, it's really useful ;)

I tested it with my current R easyconfig and I am getting this error:

```
              scales : 0.4.1    (update) [462, 30]
ggplot2 requires: R
ggplot2 requires: gtable
ggplot2 requires: stats
ggplot2 requires: scales
ggplot2 requires: lazyeval
ggplot2 requires: reshape2
ggplot2 requires: plyr
ggplot2 requires: MASS
ggplot2 requires: grid
ggplot2 requires: tibble
ggplot2 requires: digest
Traceback (most recent call last):
  File "./easy_update.py", line 439, in <module>
    module.update_exts()
  File "./easy_update.py", line 148, in update_exts
    self.check_package(list(pkg))
  File "./easy_update.py", line 134, in check_package
    self.check_package([depend, 'x'])
  File "./easy_update.py", line 107, in check_package
    pkg_ver, depends = self.get_package_info(pkg)
  File "./easy_update.py", line 309, in get_package_info
    pkg[2] = 'ext_options'
IndexError: list assignment index out of range
```

This is the easyconfig I used for testing:

https://gist.github.com/52d482b71691aea071adf27efa7659b4

**Comment by fizwit** [comment]
thanks for using easy_update.  I have fixed this issue.  clone from master or tag v1.0.0
I have tested against your EB file with success.  Thanks for providing more test data.
 
https://gist.github.com/fizwit/6227039877793d0b445c70c2aea3d3ae

**Comment by pescobar** [comment]
thanks for the quick fix!
